# (PART) Annuities {-}

#  Annuity Basics

##  6.1  Effective and Equivalent Interest Rates {-}

*  What is the effective interest rate corresponding to a nominal annual rate of:

    a. 8% compounded semiannually?
    b. 8% compounded quarterly?
    c. 8% compounded monthly?

    *   8.16% compounded annually, 8.24% compounded annually and 8.3% compounded annually  [Click here for full solution](https://youtu.be/iwRJ9krWYKU)
<p>&nbsp;</p>


*  Which of the following nominal interest rates has the highest effective rate: 11% compounded annually, 10.9% compounded semiannually, 10.8% compounded quarterly, or 10.7% compounded monthly?
    *  10.8% compounded quarterly   [Click here for full solution](https://youtu.be/JPjfHkmCcCU)     
<p>&nbsp;</p>


*  What semiannually compounded rate is equivalent to 8.5% compounded quarterly?
    *   8.59% compounded semiannually  [Click here for full solution](https://youtu.be/h81emqhwjZQ)
<p>&nbsp;</p>


*  A bank offers a rate of 3.0% compounded semiannually on a GIC. What monthly
compounded rate should the bank offer to make people indifferent between the alternatives?
    *   2.98% compounded monthly  [Click here for full solution](https://youtu.be/zMISF_LwHnc)
<p>&nbsp;</p>


*  After completing your tax return, you discover that you owe income tax. You can either pay the late payment penalty at 4% compounded daily for one year or borrow the money you need to pay your taxes. Below what semiannually compounded rate will the loan cost you less in interest than the penalty?
    *  4.04% compounded semiannually   [Click here for full solution](https://youtu.be/TCnVAc3DeP8)
<p>&nbsp;</p>




*  A bank pays 2.5% compounded semiannually on a GIC. For you to prefer an annually compounded GIC of the same maturity, what value must its nominal
interest rate exceed?
    *   2.516% compounded annually  [Click here for full solution](https://youtu.be/mEqZoWbjC1Q)
<p>&nbsp;</p>


##  6.2  Annuities {-}

*  Ken plans on contributing $8,000 every year to his TFSA. What is the future value after 20 years if the funds earn 4.25% compounded annually?
    *   \$244,500.01  [Click here for full solution](https://youtu.be/9T4ygkJbgiA)
<p>&nbsp;</p>


*  Inga plans to invest $190 every month into a fund. If the fund generates an overall rate of return of 6% compounded monthly, what will Inga's investment be worth after 8.5 years?
    *   $625,200.70  [Click here for full solution](https://youtu.be/Ppl3w4CZizc)
<p>&nbsp;</p>





*  Clint has made contributions of \$2500 to his RRSP at the end of every six months for the past 10 years. The plan has earned 9.25% compounded semiannually. He has just moved the funds to another plan that earns 8.5% compounded quarterly. He will now contribute \$1500 at the end of every three months. What total amount will Clint have in the plan seven years
from now?
    *  $199,769.23    [Click here for full solution](https://youtu.be/fqOHUa8DhOY)
<p>&nbsp;</p>


*  An ordinary annuity consists of quarterly payments of $250 for 6 years. What is the annuity’s present value, discounting at 8% compounded quarterly?
    *  \$4,728.48   [Click here for full solution](https://youtu.be/vDdH3LJB_KU)
<p>&nbsp;</p>


*  How much will it cost to purchase an ordinary annuity delivering semiannual payments of $5000 for 13.5 years if the money used to purchase the annuity can earn 7.5% compounded semiannually?
    *  \$83,986.43   [Click here for full solution](https://youtu.be/dgowP2pbgm8)
<p>&nbsp;</p>








*  A Government of Canada bond will pay \$150 at the end of every six months for the next 15 years, and an additional \$2000 lump payment at the end of the 15 years. What is the appropriate price to pay if you require a rate of return of 5.25% compounded semiannually?
    *   $4,007.10  [Click here for full solution](https://youtu.be/ZXOKP9sLZOk)
<p>&nbsp;</p>



##  6.3  Calculating the Periodic Payment and Number of Payments {-}

*  The interest rate on a \$200,000 loan is 6.5% compounded monthly. What must be the monthly payment for the loan to be repaid in: a. 5 years? b. 10 years?
    *  \$3913.23 and \$2270.96   [Click here for full solution](https://youtu.be/4hUcaKdYPXg)
<p>&nbsp;</p>


*  Grant financed the $3500 purchase price of his new fridge and freezer with monthly payments at 3.4% compounded monthly made over two years. What will be the amount of each payment?
    *  $151.05   [Click here for full solution](https://youtu.be/PoPoR1DjugU)
<p>&nbsp;</p>



*  For \$400,000, James purchased an annuity that delivers end-of-quarter payments of \$6500.  If the funds earn 4.5% compounded quarterly, what is the term of the annuity?
    *  N = 106, Term = 26.5 years   [Click here for full solution](https://youtu.be/S8gAgJt0NDY)
<p>&nbsp;</p>


*  For how long has Kevin been making end-of-quarter contributions of \$1300 to his RRSP if the RRSP has earned 4.35% compounded quarterly and is currently worth \$85,000?
    *   N = 50, and term = 12.5 years  [Click here for full solution](https://youtu.be/08e70cVxDas)
<p>&nbsp;</p>




##  6.4  Ordinary General Annuities {-}

*  An annuity consists of end-of-month payments of $250 continuing for 6.5 years. Based on a nominal rate of 8% compounded quarterly, calculate the annuity’s: a. Present value. b. Future value.
    *   PV = \$15,190.94, FV = \$25,420.79  [Click here for full solution](https://youtu.be/2qN_v-u8uL8)
<p>&nbsp;</p>


*  An annuity consists of semiannual payments of $1500 for a term of 8.5 years. Using a nominal rate of 7% compounded quarterly, calculate the ordinary annuity’s: a. Present value. b. Future value.
    *  PV = \$18,931.14, FV = \$34,146.55   [Click here for full solution](https://youtu.be/X0DQ5J4SrY8)
<p>&nbsp;</p>


*  Kelli is trying to decide if she should make regular month-end \$200 deposits to her TFSA or deposit \$650 at the end of every three months instead. How much larger is the option with the higher future value after 20 years if both investments earn 4.25% compounded annually?
    *  $650 payments (by about \$5949.50)   [Click here for full solution](https://youtu.be/ldkUwunlYEc)
<p>&nbsp;</p>


*  Year-end contributions of $1200 will be made to a TFSA for 25 years. What will be the future value of the account if it earns 7% compounded monthly for the first 10 years and 8% compounded semiannually thereafter?
    *  $87,351   [Click here for full solution](https://youtu.be/HXB9VUpZyIM)
<p>&nbsp;</p>


*  Fiona has just made her ninth annual \$2000 contribution to her RRSP. She now plans to make semiannual contributions of \$2000. The first contribution will be made six months from now. How much will she have in her RRSP 15 years from now if the plan has earned and will continue to earn 8% compounded quarterly?
    *  \$195,703.19   [Click here for full solution](https://youtu.be/nQWOwaJQih8)
<p>&nbsp;</p>




##  6.5  Using the TI BAII plus Calculator for Annuities {-}

*  You open a bank account by making an initial deposit of \$5000.  You then add to the account by making month-end payments of \$250.  If the account earns at a rate of 4.5% compounded weekly, determine the future value of the account after five years.
    *  $23,050.16   [Click here for full solution]()
<p>&nbsp;</p>



*  An investment pays you \$350 at the end of every quarter for three years, plus a lump-sum payment of \$4500 at the end of the last period.  If the current interest rate is 1.75% compounded monthly, determine the fair market value today of the investment.
    *  $8352.80   [Click here for full solution]()
<p>&nbsp;</p>


*  Greg sold his car to Jenny for \$3000 down and monthly payments of \$350 for 3.5 years, including interest at 6.5% compounded monthly. What was the selling price of the car?
    *  $16,116.17   [Click here for full solution]()
<p>&nbsp;</p>



*  Your client plans to invest $3000 at the end of each year. The rate of return on the investment is 8.5% compounded annually. What will be the value of the investment at the end of the 10 years?
    *  $509,955.29   [Click here for full solution]()
<p>&nbsp;</p>


*  Julia’s monthly payments of $525 will pay off her mortgage loan in 8 years and 5 months. The interest rate on her mortgage is 5.6% compounded monthly. What is the current balance on the loan?
    *   $42,203.90  [Click here for full solution]()
<p>&nbsp;</p>




*  Janet intends to save for holidays by contributing $400 at the end
of each month to an investment plan. At the end of every three years, she will withdraw $12,000 for a trip abroad. If the plan earns 6% compounded monthly, what will be the plan’s balance after seven years?
    *  $16,599.60   [Click here for full solution]()
<p>&nbsp;</p>

